[View in Colaboratory](https://colab.research.google.com/github/maab5669/iPython_Notebooks/blob/master/Getting_started_with_BigQuery.ipynb)

# Before you begin


1.   Use the [Cloud Resource Manager](https://console.cloud.google.com/cloud-resource-manager) to Create a Cloud Platform project if you do not already have one.
2.   [Enable billing](https://support.google.com/cloud/answer/6293499#enable-billing) for the project.
3.   [Enable BigQuery](https://console.cloud.google.com/flows/enableapi?apiid=bigquery) APIs for the project.

### Declare the Cloud project ID which will be used throughout this notebook

In [9]:
project_id = 'jlr-dl-vdm-vf'

### Provide your credentials to the runtime

In [10]:
from google.colab import auth
auth.authenticate_user()

# Use BigQuery through Pandas

[Pandas GBQ Documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_gbq.html)

The [GSOD sample table](https://bigquery.cloud.google.com/table/bigquery-public-data:samples.gsod) contains weather information collected by NOAA, such as precipitation amounts and wind speeds from late 1929 to early 2010.

### Sample approximately 2000 random rows

In [11]:
import pandas as pd

sample_count = 2000
row_count = pd.io.gbq.read_gbq('''
  SELECT 
    COUNT(*) as total
  FROM [jlr-dl-vdm-vf:mike_b_test.scan_data_with_passfail_new3]''', project_id=project_id, verbose=False).total[0]

df = pd.io.gbq.read_gbq('''
  SELECT
    *
  FROM
    [jlr-dl-vdm-vf:mike_b_test.scan_data_with_passfail_new3]
  WHERE RAND() < %d/%d
''' % (sample_count, row_count), project_id=project_id, verbose=False)

print('Full dataset has %d rows' % row_count)

Full dataset has 2469258 rows

### Describe the sampled data

In [12]:
df.describe()

           release
count  1931.000000
mean    121.727084
std      19.276407
min      79.000000
25%     105.000000
50%     123.000000
75%     140.000000
max     151.000000

### View the first 10 rows

In [13]:
df.head(10)

,load_date,pfb_VIN,pfb_Model,pfb_ModelYear,release,pfb_AppVersion,pfb_STATE,pfb_Start_time,pfb_End_time,pfb_Start_tag,...,processor,processorInfo,availableMemory,physicalMemory,deviceInfo,osService,status_status,Session_Name,topix_code,FailureCause
0,2018-02-05,SALGA2FVXHA378741,L405,2017,130,109.#130,success,2018-01-02 13:21:00,2018-01-02 13:21:00,02.01.2018 13:21:55517 console - Running flow ...,...,None,None,None,None,None,None,passed,PFFB_SALGA2FVXHA378741_UNKNOWNVERSION_M0034212...,M003421200,None
1,2018-02-05,SALYA2BX8JA709799,L560,2018,114,97.#114,success,2017-11-03 17:26:23,2017-11-03 17:27:16,03.11.2017 17:26:23624 console - Running flow ...,...,None,None,None,None,None,None,passed,PFFB_SALYA2BX8JA709799_114_M003421036_20171103...,M003421036,None
2,2018-02-05,SAJAK4EV2JCP20329,X760,2018,89,76.#89,success,2017-07-15 15:48:08,2017-07-15 15:49:59,15.07.2017 15:48:08866 console - Running flow ...,...,None,None,None,None,None,None,passed,,None,None
3,2018-02-05,SALRA2BN2JA048497,L462,2018,130,109.#130,fail,2017-12-27 12:38:12,2017-12-27 12:38:12,27.12.2017 12:38:12548 console - Running flow ...,...,None,None,None,None,None,None,passed/failed,PFFB_SALRA2BN2JA048497_UNKNOWNVERSION_N0050000...,N005000069,GWM Not Identified (CCF Function)
4,2018-03-16,SALWA2EK2HA174986,L494,2017,146,120.#146,success,2018-03-15 14:26:16,2018-03-15 14:32:11,15.03.2018 14:26:16767 console - Running flow ...,...,Intel(R) Core(TM) i5-3437U CPU @ 1.90GHz,"id=""4DTAA71461"">x86 Family 6 Model 58 Steppi...",1.1 GiB,3.4 GiB,2171AAG44D056924DTAA71461BFEBFBFF000306A9,7 SP1 build 7601,passed,PFFB_SALWA2EK2HA174986_146_M115401181_20180315...,M115401181,None
5,2018-02-05,SAJDB1BV8JCK48301,X152,2018,110,93.#110s,success,2017-10-09 09:10:51,2017-10-09 09:14:35,09.10.2017 09:10:51092 console - Running flow ...,...,None,None,None,None,None,None,passed,PFFB_SALWA2FV2HA150244_110_M003421102_20171011...,M003421102,None
6,2018-02-05,SALGA2EJ2HA371118,L405,2017,111,94.#111,fail,2017-10-19 12:03:59,2017-10-19 12:09:08,19.10.2017 12:03:59104 console - Running flow ...,...,None,None,None,None,None,None,passed/failed,PFFB_SALGA2EJ2HA371118_111_M2400A3208_20171019...,M2400A3208,Undetermined Error (WIP)
7,2018-02-05,SALWA2FVXHA173657,L494,2017,118,101.#118,success,2017-11-20 15:26:04,2017-11-20 15:31:59,20.11.2017 15:26:04652 console - Running flow ...,...,None,None,None,None,None,None,passed/failed,PFFB_SALWA2FVXHA173657_118_M003421151_20171120...,M003421151,None
8,2018-02-05,SALYM2RVXJA706348,L560,2018,95,82.#95,success,2017-08-08 17:44:05,2017-08-08 17:44:05,08.08.2017 17:44:05777 console - Running flow ...,...,None,None,None,None,None,None,passed/failed,,None,None
9,2018-02-05,SALYA2AN4JA713493,L560,2018,95,82.#95,fail,2017-08-10 11:34:02,2017-08-10 11:34:04,10.08.2017 11:34:02962 console - Running flow ...,...,None,None,None,None,None,None,failed,,None,GWM Not Identified (CCF Function)

In [14]:

df.sort_values('load_date', ascending=False).head(10)[['pfb_VIN','release']]

                pfb_VIN  release
1286  SALWA2FK3HA683015      151
536   SAJDA1BV9JCK49363      148
609   L2CCA2B87JG399772      148
242   SALRA2BK0JA060492      145
1476  SALWA2EE2HA155168      148
160   SALGA2EJ3HA367689      151
470   SALRA2AKXHA001705      151
611   SALWA2AN3JA187560      148
1605  SALVA2AN0JH313585      151
497   SADFB2DN9J1Z14592      148

# Use BigQuery through google.cloud.bigquery

[Documentation](https://googlecloudplatform.github.io/google-cloud-python/latest/bigquery/usage.html)

In [0]:
from google.cloud import bigquery

client = bigquery.Client(project=project_id)

for dataset in client.list_datasets():
  print(dataset.dataset_id)